"""
Course-scoped management endpoints.

The question bank ("banco de questoes") belongs to the course: every question a
professor uploads, reviews or deletes here is visible to every student in the
course, whichever module they entered the widget from. Questions generated by AI
still record the module their material came from (Quiz.module_id), but that is
provenance only - never a scope.
"""
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File as FastAPIFile
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List, Optional
import logging

from app.core.database import get_db
from app.core.config import settings
from app.core.super_admin_auth import get_current_professor_or_super_admin
from app.models import Course as CourseModel

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v2/courses", tags=["courses"])


# ============================
# Quiz Upload & Extraction
# ============================


class ExtractedQuestionItem(BaseModel):
    question: str
    options: dict
    correct_answer: str
    difficulty: str = "medium"
    concepts: List[str] = []


class UploadQuizResponse(BaseModel):
    status: str
    message: str
    extracted_count: int
    questions: List[dict]
    course_id: int
    job_id: Optional[int] = None


class QuizUploadJobDto(BaseModel):
    id: int
    course_id: int
    status: str
    extracted_count: int
    error_message: Optional[str] = None
    original_filename: Optional[str] = None
    processed_at: Optional[str] = None
    created_at: Optional[str] = None


class ConfirmQuizzesRequest(BaseModel):
    questions: List[dict]
    uploaded_file_id: Optional[int] = None


class ConfirmQuizzesResponse(BaseModel):
    status: str
    message: str
    saved_count: int
    course_id: int


@router.post("/{course_id}/upload-quiz-file", status_code=202)
async def upload_quiz_file(
    course_id: int,
    file: UploadFile = FastAPIFile(...),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_professor_or_super_admin),
):
    """
    Upload a file containing quiz questions for async AI extraction.

    Accepts: PDF, DOCX, XLSX, CSV, TXT (max 10 MB)
    Returns 202 Accepted immediately with a job_id.
    Poll GET /{course_id}/quiz-upload-jobs/{job_id} to check status.
    When status=completed, GET /{course_id}/quiz-upload-jobs/{job_id}/questions returns the extracted questions.
    """
    import logging
    logger = logging.getLogger(__name__)

    try:
        course = db.query(CourseModel).filter(CourseModel.id == course_id).first()
        if not course:
            raise HTTPException(status_code=404, detail="Course not found")

        # Validate file type
        allowed_extensions = {"pdf", "docx", "doc", "xlsx", "xls", "csv", "txt"}
        file_ext = file.filename.rsplit(".", 1)[-1].lower() if file.filename else ""
        if file_ext not in allowed_extensions:
            raise HTTPException(
                status_code=400,
                detail=f"Unsupported file type: .{file_ext}. Allowed: {', '.join(allowed_extensions)}"
            )

        # Read and validate file size
        content = await file.read()
        if len(content) > 10 * 1024 * 1024:  # 10MB limit
            raise HTTPException(status_code=400, detail="File too large. Maximum 10MB.")

        # Create QuizUploadJob record (pending) first to get the ID
        from app.models import QuizUploadJob
        job = QuizUploadJob(
            course_id=course_id,
            status="pending",
            extracted_count=0,
            original_filename=file.filename,
        )
        db.add(job)
        db.commit()
        db.refresh(job)

        # Upload file to S3: quiz-upload-jobs/courses/{course_id}/{job_id}/{filename}
        from app.services.blob_storage import BlobStorageService
        import asyncio
        import boto3

        s3_key = f"quiz-upload-jobs/courses/{course_id}/{job.id}/{file.filename}"
        try:
            blob = BlobStorageService()
            s3 = boto3.client(
                "s3",
                region_name=settings.AWS_REGION,
                aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            )
            await asyncio.to_thread(
                s3.put_object,
                Bucket=settings.S3_BUCKET_NAME,
                Key=s3_key,
                Body=content,
                ContentType=file.content_type or "application/octet-stream",
            )
        except Exception as upload_err:
            logger.error(f"Failed to upload quiz file to S3: {upload_err}")
            job.status = "failed"
            job.error_message = "Failed to upload file to storage"
            db.commit()
            raise HTTPException(status_code=500, detail="Failed to upload file")

        job.input_s3_key = s3_key
        db.commit()

        # Send SQS message (non-blocking) — worker will extract and store questions
        quiz_upload_url = settings.SQS_QUIZ_UPLOAD_QUEUE_URL
        if quiz_upload_url:
            try:
                import json as _json
                sqs = boto3.client(
                    "sqs",
                    region_name=settings.AWS_REGION,
                    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
                )
                await asyncio.to_thread(
                    sqs.send_message,
                    QueueUrl=quiz_upload_url,
                    MessageBody=_json.dumps({"job_id": job.id, "course_id": course_id}),
                )
                logger.info(f"📨 SQS quiz-upload message sent for job {job.id}")
            except Exception as sqs_err:
                # Non-fatal: job is created, but SQS message failed
                logger.warning(f"⚠️ Failed to send SQS message for quiz upload job {job.id}: {sqs_err}")
        else:
            logger.warning("SQS_QUIZ_UPLOAD_QUEUE_URL not configured — quiz upload job will not process automatically")

        logger.info(f"Created quiz upload job {job.id} for course {course_id} ({file.filename})")

        return {
            "status": "pending",
            "message": f"File uploaded. Processing in background — check job status to review extracted questions.",
            "job_id": job.id,
            "course_id": course_id,
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error creating quiz upload job: {type(e).__name__}: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to create quiz upload job: {str(e)[:500]}"
        )


@router.get("/{course_id}/quiz-upload-jobs", response_model=List[QuizUploadJobDto])
async def list_quiz_upload_jobs(
    course_id: int,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_professor_or_super_admin),
):
    """List all quiz upload jobs for a course, newest first."""
    from app.models import QuizUploadJob
    jobs = (
        db.query(QuizUploadJob)
        .filter(QuizUploadJob.course_id == course_id)
        .order_by(QuizUploadJob.id.desc())
        .all()
    )
    return [
        QuizUploadJobDto(
            id=j.id,
            course_id=j.course_id,
            status=j.status,
            extracted_count=j.extracted_count,
            error_message=j.error_message,
            original_filename=j.original_filename,
            processed_at=j.processed_at.isoformat() if j.processed_at else None,
            created_at=j.created_at.isoformat() if j.created_at else None,
        )
        for j in jobs
    ]


@router.get("/{course_id}/quiz-upload-jobs/{job_id}/questions")
async def get_quiz_upload_job_questions(
    course_id: int,
    job_id: int,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_professor_or_super_admin),
):
    """
    Return the extracted questions for a completed quiz upload job.
    Only available when status=completed.
    """
    import json as _json
    from app.models import QuizUploadJob
    job = db.query(QuizUploadJob).filter(
        QuizUploadJob.id == job_id,
        QuizUploadJob.course_id == course_id,
    ).first()
    if not job:
        raise HTTPException(status_code=404, detail="Quiz upload job not found")
    if job.status != "completed":
        raise HTTPException(status_code=400, detail=f"Job is not completed (status: {job.status})")
    if not job.extracted_questions_json:
        raise HTTPException(status_code=400, detail="No extracted questions available for this job")

    questions = _json.loads(job.extracted_questions_json)
    return {
        "status": "success",
        "message": f"Extracted {len(questions)} questions. Review and confirm to save.",
        "extracted_count": len(questions),
        "questions": questions,
        "course_id": course_id,
        "job_id": job_id,
    }


@router.post("/{course_id}/confirm-extracted-quizzes", response_model=ConfirmQuizzesResponse)
async def confirm_extracted_quizzes(
    course_id: int,
    request: ConfirmQuizzesRequest,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_professor_or_super_admin),
):
    """
    Confirm and save extracted quiz questions after professor review.

    The professor reviews the extracted questions (from upload-quiz-file),
    can edit/remove questions, then submits the final list to save.
    """
    import logging
    logger = logging.getLogger(__name__)

    try:
        course = db.query(CourseModel).filter(CourseModel.id == course_id).first()
        if not course:
            raise HTTPException(status_code=404, detail="Course not found")

        if not request.questions:
            raise HTTPException(status_code=400, detail="No questions to save")

        from app.services.quiz_extractor import QuizExtractorService

        extractor = QuizExtractorService(course, db)
        saved = extractor.save_extracted_questions(
            request.questions,
            uploaded_file_id=request.uploaded_file_id
        )

        return ConfirmQuizzesResponse(
            status="success",
            message=f"Successfully saved {len(saved)} quiz questions",
            saved_count=len(saved),
            course_id=course_id
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error saving extracted quizzes: {type(e).__name__}: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to save quizzes: {str(e)[:500]}"
        )


# ================================
# Quiz Management Endpoints
# ================================

class ListQuizzesResponse(BaseModel):
    quizzes: List[dict]
    total: int
    course_id: int


@router.get("/{course_id}/quizzes", response_model=ListQuizzesResponse)
async def list_course_quizzes(
    course_id: int,
    difficulty: Optional[str] = None,
    source: Optional[str] = None,
    module_id: Optional[int] = None,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_professor_or_super_admin),
):
    """
    List every quiz question in the course's question bank.

    Optional filters:
    - difficulty: easy, medium, hard
    - source: ai_generated, uploaded, manual
    - module_id: only questions generated from that module's material
    """
    from app.models import Quiz

    course = db.query(CourseModel).filter(CourseModel.id == course_id).first()
    if not course:
        raise HTTPException(status_code=404, detail="Course not found")

    query = db.query(Quiz).filter(Quiz.course_id == course_id)

    if difficulty and difficulty in ("easy", "medium", "hard"):
        query = query.filter(Quiz.difficulty == difficulty)

    if source and source in ("ai_generated", "uploaded", "manual"):
        query = query.filter(Quiz.source == source)

    if module_id:
        query = query.filter(Quiz.module_id == module_id)

    quizzes = query.order_by(Quiz.question_number).all()

    return ListQuizzesResponse(
        quizzes=[q.to_dict() for q in quizzes],
        total=len(quizzes),
        course_id=course_id
    )


@router.delete("/{course_id}/quizzes/{quiz_id}")
async def delete_quiz_question(
    course_id: int,
    quiz_id: int,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_professor_or_super_admin),
):
    """
    Delete a single quiz question from the course's question bank.
    """
    from app.models import Quiz

    course = db.query(CourseModel).filter(CourseModel.id == course_id).first()
    if not course:
        raise HTTPException(status_code=404, detail="Course not found")

    quiz = db.query(Quiz).filter(Quiz.id == quiz_id, Quiz.course_id == course_id).first()
    if not quiz:
        raise HTTPException(status_code=404, detail="Quiz question not found")

    db.delete(quiz)
    db.commit()

    return {"status": "success", "message": "Quiz question deleted"}
